name: "ssh"
shortDesc: "Run a shell on the container using a given username. Usage: kubectl ssh -u root ingestion-0"
example: "kubectl ssh rabbitmq-1 -u root"
command: ./ssh.sh
flags:
  - name: "user"
    shorthand: "u"
    desc: "Run as user."
    defValue: ""
  - name: "pod"
    shorthand: "p"
    desc: "pod name"
    defValue: ""
