name: "ssh"
shortDesc: "Exec user plugin via mikelorant"
longDesc: >
  Exec as a specified user into a container.
example: "kubectl ssh rabbitmq-2"
command: "./ssh.sh"
flags:
  - name: "user"
    shorthand: "u"
    desc: "Username or UID. If omitted, will use root."
    defValue: "root"
  - name: "container"
    shorthand: "c"
    desc: "Container name. Used when running multiple containers within a pod. If omitted, the first container in the pod will be chosen."
  - name: "namespace"
    shorthand: "n"
    desc: "Optional. If not provided, the current namespace is used."
