name: "ssh"
shortDesc: "Exec user plugin via mikelorant"
longDesc: >
  Exec as a specified user into a container.
example: ""
command: "./ssh.sh"
flags:
  - name: "user"
    shorthand: "u"
    desc: "Username or UID. If omitted, will use root"
    defValue: "root"
  - name: "container"
    shorthand: "c"
    desc: "Container name. If omitted, the first container in the pod will be chosen"
