name: "switch"
shortDesc: "Switch context"
longDesc: >
  Switches your current context to the namespace specified.
  - kubectl switch <namespace>
  - kubectl switch cluster <cluster>
  - kubectl switch cluster -l
command: ./switch.sh $@
flags:
  - name: "list"
    shorthand: "l"
    desc: "List and select from available clusters. Can only be used alongside 'cluster', i.e., 'kubectl switch cluster -l'"
