name: "deploy"
shortDesc: "Apply Namespace Specific Values to the File(s) Specified."
longDesc: >
  Replace all fields which contain a namespace specific value (i.e., external-dns.alpha.kubernetes.io/hostname).
  This is handled automatically at run-time and does not write to any file.
example: "kubectl plugin deploy -n staging -i nexus.myOrg.com/rabbitmq:v1.0 -f rabbitmq.yml"
command: ./deploy.sh
flags:
  - name: "file"
    shorthand: "f"
    desc: "[ -f ./cassandra.yml ] -- Required. File to deploy. Currently allows one per run."
    defValue: ""
  - name: "namespace"
    shorthand: "n"
    desc: "[ -n preprod ] -- Optional. Namespace/Environment to deploy to. If not provided, the current namespace is used"
    defValue: ""
  - name: "dry"
    shorthand: "d"
    desc: "[ -d true ] -- Optional. Apply a dry-run over the selected file."
    defValue: ""
  - name: "path"
    shorthand: "p"
    desc: "System managed flag."
  - name: "image"
    shorthand: "i"
    desc: "[ -i kafka:v1.0.0 | -i actions ] -- Optional. Pass the image to deploy with and ignore the image used in the manifest. If no version is passed, a list is provided to choose from (i.e., -t actions vs -t actions:v1.0.0)."
    defValue: ""
