name: "verify"
shortDesc: "Caution user when working in production"
longDesc: >
  Prompts the user when issuing a command in a production namespace.
command: ./verify.sh "$@"
flags:
  - name: "quiet"
    shorthand: "q"
    desc: "Do not prompt user while operating in production."
    defValue: "false"
  - name: "user"
    shorthand: "u"
    desc: "Run as user."
    defValue: ""
  - name: "ata"
    shorthand: "a"
    desc: "Runa."
    defValue: ""
  - name: "ba"
    shorthand: "b"
    desc: "Run as userb."
    defValue: ""
  - name: "userc"
    shorthand: "c"
    desc: "Run as userc."
    defValue: ""
  - name: "userd"
    shorthand: "d"
    desc: "Run as userd."
    defValue: ""
  - name: "users"
    shorthand: "s"
    desc: "Run as users."
    defValue: ""
  - name: "userl"
    shorthand: "l"
    desc: "Run as userl."
    defValue: ""
